import type { FaultDefinition, FaultType } from './types'
const text = (en: string, fr: string, de: string) => ({ en, fr, de })
const definitions: Record<FaultType, FaultDefinition> = {
  'collision-risk': { type: 'collision-risk', severity: 'critical', equipmentId: 'robot-1', title: text('Collision risk', 'Risque de collision', 'Kollisionsrisiko'), recoveryInstructions: text('Inspect the robot path, acknowledge, reset the motion, then retry.', 'Inspectez la trajectoire, acquittez, réinitialisez le mouvement, puis réessayez.', 'Prüfen Sie den Roboterpfad, quittieren Sie, setzen Sie die Bewegung zurück und versuchen Sie es erneut.'), requiresAcknowledgement: true, requiresReset: true, pauseWorkflow: true },
  'unreachable-target': { type: 'unreachable-target', severity: 'error', equipmentId: 'robot-1', title: text('Unreachable target', 'Cible inaccessible', 'Unerreichbares Ziel'), recoveryInstructions: text('Correct the target or robot configuration, acknowledge, then retry.', 'Corrigez la cible ou la configuration, acquittez, puis réessayez.', 'Korrigieren Sie Ziel oder Roboterkonfiguration, quittieren Sie und versuchen Sie es erneut.'), requiresAcknowledgement: true, requiresReset: false, pauseWorkflow: true },
  'cnc-fault': { type: 'cnc-fault', severity: 'critical', equipmentId: 'cnc-1', title: text('CNC fault', 'Défaut CNC', 'CNC-Fehler'), recoveryInstructions: text('Acknowledge the CNC alarm, reset the CNC, then retry the load.', 'Acquittez l’alarme CNC, réinitialisez le CNC, puis réessayez le chargement.', 'Quittieren Sie den CNC-Alarm, setzen Sie die CNC zurück und versuchen Sie das Laden erneut.'), requiresAcknowledgement: true, requiresReset: true, pauseWorkflow: true },
  'conveyor-blockage': { type: 'conveyor-blockage', severity: 'error', equipmentId: 'conveyor-1', title: text('Conveyor blockage', 'Blocage convoyeur', 'Fördererblockierung'), recoveryInstructions: text('Clear the simulated blockage, acknowledge, reset, then retry.', 'Supprimez le blocage simulé, acquittez, réinitialisez, puis réessayez.', 'Beseitigen Sie die simulierte Blockierung, quittieren und setzen Sie zurück.'), requiresAcknowledgement: true, requiresReset: true, pauseWorkflow: true },
  'missing-pallet': { type: 'missing-pallet', severity: 'error', equipmentId: 'pallet-station-1', title: text('Missing pallet', 'Palette absente', 'Palette fehlt'), recoveryInstructions: text('Supply a pallet, acknowledge the condition, then retry.', 'Présentez une palette, acquittez la condition, puis réessayez.', 'Stellen Sie eine Palette bereit, quittieren Sie den Zustand und versuchen Sie es erneut.'), requiresAcknowledgement: true, requiresReset: false, pauseWorkflow: true },
  'stale-heartbeat': { type: 'stale-heartbeat', severity: 'warning', equipmentId: 'simulator-1', title: text('Stale heartbeat', 'Heartbeat obsolète', 'Veralteter Heartbeat'), recoveryInstructions: text('Restore the heartbeat, acknowledge the warning, then retry.', 'Rétablissez le heartbeat, acquittez l’avertissement, puis réessayez.', 'Stellen Sie den Heartbeat wieder her, quittieren Sie die Warnung und versuchen Sie es erneut.'), requiresAcknowledgement: true, requiresReset: false, pauseWorkflow: true },
  'communication-loss': { type: 'communication-loss', severity: 'critical', equipmentId: 'simulator-1', title: text('Communication loss', 'Perte de communication', 'Kommunikationsverlust'), recoveryInstructions: text('Reconnect the simulated link, acknowledge, reset the session, then retry.', 'Reconnectez le lien simulé, acquittez, réinitialisez la session, puis réessayez.', 'Verbinden Sie die simulierte Verbindung erneut, quittieren Sie, setzen Sie die Sitzung zurück und versuchen Sie es erneut.'), requiresAcknowledgement: true, requiresReset: true, pauseWorkflow: true },
}
export function getFaultDefinition(type: FaultType): FaultDefinition { return definitions[type] }
export const FAULT_CATALOG = Object.values(definitions)
