/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/Alarms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AlarmDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Alarms/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AlarmDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Alarms/{id}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    by?: string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AlarmDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiErrorDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Alarms/{id}/transition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    state?: string;
                    by?: string;
                    note?: string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AlarmDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthConfigDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/dev-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["DevTokenRequest"];
                    "text/json": components["schemas"]["DevTokenRequest"];
                    "application/*+json": components["schemas"]["DevTokenRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthTokenDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiErrorDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiErrorDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthMeDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cell-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CellTemplateDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SaveCellTemplateRequest"];
                    "text/json": components["schemas"]["SaveCellTemplateRequest"];
                    "application/*+json": components["schemas"]["SaveCellTemplateRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CellTemplateDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiErrorDto"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiErrorDto"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiErrorDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cell-templates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CellTemplateDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiErrorDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SaveCellTemplateRequest"];
                    "text/json": components["schemas"]["SaveCellTemplateRequest"];
                    "application/*+json": components["schemas"]["SaveCellTemplateRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CellTemplateDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiErrorDto"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiErrorDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiErrorDto"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiErrorDto"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiErrorDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiErrorDto"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connectors/opcua": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ConnectorStatusDto"];
                        "application/json": components["schemas"]["ConnectorStatusDto"];
                        "text/json": components["schemas"]["ConnectorStatusDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connectors/mqtt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ConnectorStatusDto"];
                        "application/json": components["schemas"]["ConnectorStatusDto"];
                        "text/json": components["schemas"]["ConnectorStatusDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connectors/modbus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ConnectorStatusDto"];
                        "application/json": components["schemas"]["ConnectorStatusDto"];
                        "text/json": components["schemas"]["ConnectorStatusDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/control-authority/{scope}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    scope: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ControlAuthorityDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/control-authority/{scope}/acquire": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    scope: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AcquireControlAuthorityRequest"];
                    "text/json": components["schemas"]["AcquireControlAuthorityRequest"];
                    "application/*+json": components["schemas"]["AcquireControlAuthorityRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ControlAuthorityDto"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiErrorDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/control-authority/{scope}/takeover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    scope: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["TakeoverControlAuthorityRequest"];
                    "text/json": components["schemas"]["TakeoverControlAuthorityRequest"];
                    "application/*+json": components["schemas"]["TakeoverControlAuthorityRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ControlAuthorityDto"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiErrorDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/control-authority/{scope}/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    scope: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ReleaseControlAuthorityRequest"];
                    "text/json": components["schemas"]["ReleaseControlAuthorityRequest"];
                    "application/*+json": components["schemas"]["ReleaseControlAuthorityRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ControlAuthorityDto"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiErrorDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/control-authority/{scope}/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    scope: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["HeartbeatControlAuthorityRequest"];
                    "text/json": components["schemas"]["HeartbeatControlAuthorityRequest"];
                    "application/*+json": components["schemas"]["HeartbeatControlAuthorityRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ControlAuthorityDto"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiErrorDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/control-authority/{scope}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    limit?: number;
                };
                header?: never;
                path: {
                    scope: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ControlAuthorityEventDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/historian/telemetry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    sessionId?: string;
                    equipmentId?: string;
                    signalId?: string;
                    fromUtc?: string;
                    toUtc?: string;
                    quality?: string;
                    source?: string;
                    correlationId?: string;
                    skip?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TelemetrySampleDtoHistorianPageDto"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["IngestTelemetryBatchRequest"];
                    "text/json": components["schemas"]["IngestTelemetryBatchRequest"];
                    "application/*+json": components["schemas"]["IngestTelemetryBatchRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HistorianIngestResultDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiErrorDto"];
                    };
                };
                /** @description Too Many Requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HistorianIngestResultDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/historian/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    sessionId?: string;
                    equipmentId?: string;
                    kind?: string;
                    severity?: string;
                    code?: string;
                    fromUtc?: string;
                    toUtc?: string;
                    correlationId?: string;
                    skip?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HistorizedEventDtoHistorianPageDto"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["IngestHistorizedEventBatchRequest"];
                    "text/json": components["schemas"]["IngestHistorizedEventBatchRequest"];
                    "application/*+json": components["schemas"]["IngestHistorizedEventBatchRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HistorianIngestResultDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiErrorDto"];
                    };
                };
                /** @description Too Many Requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HistorianIngestResultDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/historian/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HistorianStatusDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JobDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateJobRequest"];
                    "text/json": components["schemas"]["CreateJobRequest"];
                    "application/*+json": components["schemas"]["CreateJobRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JobDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiErrorDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JobDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiErrorDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiErrorDto"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Jobs/{id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JobDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiErrorDto"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiErrorDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Jobs/{id}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ClaimJobRequest"];
                    "text/json": components["schemas"]["ClaimJobRequest"];
                    "application/*+json": components["schemas"]["ClaimJobRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClaimResultDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiErrorDto"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiErrorDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Jobs/{id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JobDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiErrorDto"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiErrorDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Jobs/{id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JobDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiErrorDto"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiErrorDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Jobs/{id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JobDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiErrorDto"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiErrorDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Jobs/{id}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/machine-state/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MachineStateDto"];
                    };
                };
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateMachineStateRequest"];
                    "text/json": components["schemas"]["UpdateMachineStateRequest"];
                    "application/*+json": components["schemas"]["UpdateMachineStateRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MachineStateDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mappings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SignalMappingSummaryDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mappings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SignalMappingDocumentDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiErrorDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: {
                    expectedVersion?: number;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SignalMappingDocumentDto"];
                    "text/json": components["schemas"]["SignalMappingDocumentDto"];
                    "application/*+json": components["schemas"]["SignalMappingDocumentDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SignalMappingDocumentDto"];
                    };
                };
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SignalMappingDocumentDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiErrorDto"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiErrorDto"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiErrorDto"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: {
                    expectedVersion?: number;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiErrorDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiErrorDto"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiErrorDto"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mappings/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SignalMappingDocumentDto"];
                    "text/json": components["schemas"]["SignalMappingDocumentDto"];
                    "application/*+json": components["schemas"]["SignalMappingDocumentDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SignalMappingValidationResultDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mappings/{id}/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SignalMappingApplyResultDto"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiErrorDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiErrorDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mappings/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SignalMappingAuditDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OperatorMessageDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulation-sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SimulationSessionDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiErrorDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulation-sessions/by-job/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SimulationSessionDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiErrorDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulation-sessions/{id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateSimulationStateRequest"];
                    "text/json": components["schemas"]["UpdateSimulationStateRequest"];
                    "application/*+json": components["schemas"]["UpdateSimulationStateRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SimulationSessionDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiErrorDto"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiErrorDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulation-sessions/{id}/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["HeartbeatRequest"];
                    "text/json": components["schemas"]["HeartbeatRequest"];
                    "application/*+json": components["schemas"]["HeartbeatRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SimulationSessionDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiErrorDto"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiErrorDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateTaskStatusRequest"];
                    "text/json": components["schemas"]["UpdateTaskStatusRequest"];
                    "application/*+json": components["schemas"]["UpdateTaskStatusRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiErrorDto"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiErrorDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AcquireControlAuthorityRequest: {
            mode: string;
            ownerId?: string | null;
            ownerKind?: string | null;
            /** Format: int32 */
            leaseSeconds?: number;
            correlationId?: string | null;
        };
        AlarmAuditDto: {
            action?: string;
            by?: string;
            /** Format: date-time */
            atUtc?: string;
            note?: string | null;
        };
        AlarmDto: {
            id?: string;
            code?: string;
            title?: string;
            message?: string;
            severity?: string;
            source?: string;
            jobId?: string | null;
            simulationSessionId?: string | null;
            /** Format: date-time */
            createdAtUtc?: string;
            acknowledged?: boolean;
            /** Format: date-time */
            acknowledgedAtUtc?: string | null;
            acknowledgedBy?: string | null;
            lifecycleState?: string;
            /** Format: date-time */
            firstOccurredAtUtc?: string;
            /** Format: date-time */
            lastOccurredAtUtc?: string;
            /** Format: int32 */
            occurrenceCount?: number;
            cause?: string;
            consequence?: string;
            operatorGuidance?: string;
            auditTrail?: components["schemas"]["AlarmAuditDto"][];
        };
        ApiErrorDto: {
            code?: string;
            message?: string;
            /** Format: int32 */
            status?: number;
            details?: {
                [key: string]: string[] | null;
            } | null;
        };
        AuthConfigDto: {
            mode?: string;
            developmentAuth?: boolean;
            publicDemoEnabled?: boolean;
            roles?: string[];
            warning?: string | null;
        };
        AuthMeDto: {
            subject?: string;
            name?: string | null;
            roles?: string[];
            authenticationType?: string;
        };
        AuthTokenDto: {
            accessToken?: string;
            tokenType?: string;
            /** Format: date-time */
            expiresAtUtc?: string;
            mode?: string;
            subject?: string;
            roles?: string[];
        };
        CellTemplateDto: {
            id?: string;
            name?: string;
            schemaVersion?: string;
            content?: string;
            /** Format: date-time */
            createdAtUtc?: string;
            /** Format: date-time */
            updatedAtUtc?: string;
            /** Format: int32 */
            version?: number;
            createdBy?: string | null;
            updatedBy?: string | null;
        };
        ClaimJobRequest: {
            simulatorId: string;
            correlationId?: string | null;
        };
        ClaimResultDto: {
            job?: components["schemas"]["JobDto"];
            session?: components["schemas"]["SimulationSessionDto"];
            tasks?: components["schemas"]["TaskDto"][];
        };
        ConnectorStatusDto: {
            connector?: string;
            state?: string;
            endpoint?: string | null;
            lastError?: string | null;
            /** Format: int32 */
            reconnectCount?: number;
            /** Format: int32 */
            monitoredItemCount?: number;
            /** Format: int64 */
            notificationsReceived?: number;
            /** Format: int64 */
            updatesAccepted?: number;
            /** Format: int64 */
            updatesRejected?: number;
            /** Format: int64 */
            writeAttempts?: number;
            /** Format: int64 */
            writesAccepted?: number;
            /** Format: int64 */
            writesRejected?: number;
            /** Format: date-time */
            timestampUtc?: string;
        };
        ControlAuthorityDto: {
            scope?: string;
            mode?: string;
            state?: string;
            ownerId?: string | null;
            ownerKind?: string | null;
            /** Format: date-time */
            acquiredAtUtc?: string | null;
            /** Format: date-time */
            leaseExpiresAtUtc?: string | null;
            /** Format: date-time */
            lastHeartbeatUtc?: string | null;
            /** Format: int32 */
            version?: number;
            degradedReason?: string | null;
            correlationId?: string | null;
            isPersisted?: boolean;
            diagnostic?: string | null;
        };
        ControlAuthorityEventDto: {
            id?: string;
            scope?: string;
            eventType?: string;
            mode?: string | null;
            previousMode?: string | null;
            ownerId?: string | null;
            previousOwnerId?: string | null;
            correlationId?: string | null;
            detail?: string | null;
            /** Format: date-time */
            timestampUtc?: string;
            actorId?: string | null;
            actorRole?: string | null;
        };
        CreateJobRequest: {
            name: string;
            description?: string;
            machineMode?: string;
            tasks?: components["schemas"]["CreateTaskRequest"][];
            metadata?: {
                [key: string]: string;
            };
        };
        CreateTaskRequest: {
            name: string;
            description?: string;
            partType?: string;
            palletId?: string | null;
            /** Format: int32 */
            slotRow?: number;
            /** Format: int32 */
            slotColumn?: number;
        };
        DevTokenRequest: {
            role: string;
            subject?: string | null;
            name?: string | null;
        };
        HeartbeatControlAuthorityRequest: {
            ownerId: string;
            resume?: boolean;
            /** Format: int32 */
            leaseSeconds?: number;
        };
        HeartbeatRequest: {
            simulatorId: string;
        };
        HistorianIngestResultDto: {
            /** Format: int32 */
            accepted?: number;
            /** Format: int32 */
            sampled?: number;
            /** Format: int32 */
            dropped?: number;
            /** Format: int32 */
            rejected?: number;
            enabled?: boolean;
            degraded?: boolean;
            status?: string;
            diagnostics?: string[];
        };
        HistorianSignalPolicyDto: {
            equipmentId?: string;
            signalId?: string;
            mode?: string;
            /** Format: int32 */
            intervalMilliseconds?: number;
            /** Format: double */
            deadband?: number;
        };
        HistorianStatusDto: {
            enabled?: boolean;
            retentionEnabled?: boolean;
            schemaVersion?: string;
            /** Format: int64 */
            sampleDocumentCount?: number;
            /** Format: int64 */
            eventDocumentCount?: number;
            /** Format: int64 */
            estimatedStorageBytes?: number;
            /** Format: int32 */
            sampledSignalCount?: number;
            /** Format: int32 */
            maxAgeDays?: number;
            /** Format: int64 */
            maxSamplesPerSignal?: number;
            /** Format: int64 */
            maxEventDocuments?: number;
            /** Format: date-time */
            lastPrunedAtUtc?: string | null;
            /** Format: int64 */
            lastPruneDeletedCount?: number;
            policies?: components["schemas"]["HistorianSignalPolicyDto"][];
        };
        HistorizedEventDto: {
            id?: string;
            schemaVersion?: string;
            /** Format: date-time */
            timestampUtc?: string;
            kind?: string;
            sessionId?: string | null;
            runId?: string | null;
            equipmentId?: string | null;
            severity?: string;
            code?: string;
            payload?: string;
            source?: string;
            /** Format: int64 */
            sequence?: number | null;
            correlationId?: string | null;
        };
        HistorizedEventDtoHistorianPageDto: {
            items?: components["schemas"]["HistorizedEventDto"][];
            /** Format: int64 */
            totalCount?: number;
            /** Format: int32 */
            skip?: number;
            /** Format: int32 */
            limit?: number;
        };
        IngestHistorizedEventBatchRequest: {
            events?: components["schemas"]["IngestHistorizedEventRequest"][];
            sourceId?: string | null;
        };
        IngestHistorizedEventRequest: {
            /** Format: date-time */
            timestampUtc?: string;
            kind?: string;
            sessionId?: string | null;
            runId?: string | null;
            equipmentId?: string | null;
            severity?: string;
            code?: string;
            payload?: string;
            source?: string;
            /** Format: int64 */
            sequence?: number | null;
            correlationId?: string | null;
        };
        IngestTelemetryBatchRequest: {
            samples?: components["schemas"]["IngestTelemetrySampleRequest"][];
            sourceId?: string | null;
        };
        IngestTelemetrySampleRequest: {
            /** Format: date-time */
            timestampUtc?: string;
            sessionId?: string | null;
            runId?: string | null;
            equipmentId: string;
            signalId: string;
            /** Format: double */
            numericValue?: number | null;
            textValue?: string | null;
            valueType?: string;
            quality?: string;
            source?: string;
            origin?: string;
            correlationId?: string | null;
        };
        JobDto: {
            id?: string;
            name?: string;
            description?: string;
            status?: string;
            machineMode?: string;
            /** Format: date-time */
            createdAtUtc?: string;
            /** Format: date-time */
            updatedAtUtc?: string;
            /** Format: date-time */
            startedAtUtc?: string | null;
            /** Format: date-time */
            completedAtUtc?: string | null;
            /** Format: date-time */
            pausedAtUtc?: string | null;
            /** Format: date-time */
            stoppedAtUtc?: string | null;
            /** Format: int32 */
            currentTaskIndex?: number;
            /** Format: int32 */
            progressPercent?: number;
            simulationSessionId?: string | null;
            metadata?: {
                [key: string]: string;
            };
            /** Format: int32 */
            version?: number;
        };
        MachineStateDto: {
            id?: string;
            simulationSessionId?: string | null;
            machineMode?: string;
            simulationStatus?: string;
            robotState?: string;
            cncState?: string;
            currentPhase?: string;
            currentPalletId?: string | null;
            currentTaskId?: string | null;
            currentPartId?: string | null;
            /** Format: int32 */
            currentSlotRow?: number;
            /** Format: int32 */
            currentSlotColumn?: number;
            isRunning?: boolean;
            isPaused?: boolean;
            /** Format: date-time */
            lastUpdatedAtUtc?: string;
        };
        OperatorMessageDto: {
            id?: string;
            title?: string;
            message?: string;
            type?: string;
            source?: string;
            jobId?: string | null;
            simulationSessionId?: string | null;
            /** Format: date-time */
            createdAtUtc?: string;
            read?: boolean;
            /** Format: date-time */
            readAtUtc?: string | null;
        };
        ReleaseControlAuthorityRequest: {
            ownerId: string;
            correlationId?: string | null;
        };
        SaveCellTemplateRequest: {
            name: string;
            content: string;
        };
        SignalMappingApplyEntryDto: {
            protocol?: string;
            status?: string;
            /** Format: int32 */
            entryCount?: number;
            reason?: string | null;
        };
        SignalMappingApplyResultDto: {
            applied?: boolean;
            mappingId?: string;
            /** Format: int32 */
            version?: number;
            protocols?: components["schemas"]["SignalMappingApplyEntryDto"][];
            diagnostics?: components["schemas"]["SignalMappingDiagnosticDto"][];
            /** Format: date-time */
            appliedAtUtc?: string;
            appliedBy?: string | null;
        };
        SignalMappingAuditDto: {
            action?: string;
            mappingId?: string;
            /** Format: int32 */
            version?: number;
            by?: string;
            /** Format: date-time */
            atUtc?: string;
            detail?: string | null;
        };
        SignalMappingDiagnosticDto: {
            severity?: string;
            code?: string;
            message?: string;
            path?: string | null;
            entryId?: string | null;
        };
        SignalMappingDocumentDto: {
            schemaVersion?: string;
            id?: string;
            name?: string;
            entries?: components["schemas"]["SignalMappingEntryDto"][];
            /** Format: int32 */
            version?: number;
            description?: string | null;
        };
        SignalMappingEntryDto: {
            id?: string;
            name?: string;
            internalSignalId?: string;
            equipmentId?: string;
            protocol?: string;
            direction?: string;
            dataType?: string;
            /** Format: double */
            scale?: number;
            /** Format: double */
            offset?: number;
            unit?: string | null;
            enabled?: boolean;
            target?: components["schemas"]["SignalMappingTargetDto"];
            description?: string | null;
            notes?: string | null;
        };
        SignalMappingSummaryDto: {
            id?: string;
            name?: string;
            /** Format: int32 */
            version?: number;
            /** Format: int32 */
            entryCount?: number;
            valid?: boolean;
            /** Format: date-time */
            updatedAtUtc?: string;
        };
        SignalMappingTargetDto: {
            nodeId?: string | null;
            topic?: string | null;
            payloadField?: string | null;
            retain?: boolean | null;
            area?: string | null;
            /** Format: int32 */
            address?: number | null;
            /** Format: int32 */
            width?: number | null;
            /** Format: int32 */
            bitIndex?: number | null;
            byteOrder?: string | null;
            wordOrder?: string | null;
            signed?: boolean | null;
            /** Format: int32 */
            unitId?: number | null;
            addressConvention?: string | null;
        };
        SignalMappingValidationResultDto: {
            valid?: boolean;
            diagnostics?: components["schemas"]["SignalMappingDiagnosticDto"][];
        };
        SimulationSessionDto: {
            id?: string;
            jobId?: string;
            status?: string;
            /** Format: date-time */
            startedAtUtc?: string;
            /** Format: date-time */
            endedAtUtc?: string | null;
            isPaused?: boolean;
            currentPhase?: string;
            currentPalletId?: string | null;
            currentTaskId?: string | null;
            currentPartId?: string | null;
            /** Format: int32 */
            machinedCount?: number;
            /** Format: int32 */
            remainingCount?: number;
            /** Format: int32 */
            totalCount?: number;
            /** Format: date-time */
            lastHeartbeatUtc?: string;
            simulatorId?: string | null;
            correlationId?: string | null;
            /** Format: int32 */
            version?: number;
            scenarioId?: string | null;
            scenarioActivityId?: string | null;
            /** Format: int32 */
            scenarioProgress?: number;
        };
        TakeoverControlAuthorityRequest: {
            mode: string;
            ownerId: string;
            ownerKind?: string | null;
            confirm?: boolean;
            confirmationToken?: string | null;
            /** Format: int32 */
            leaseSeconds?: number;
            correlationId?: string | null;
        };
        TaskDto: {
            id?: string;
            jobId?: string;
            name?: string;
            description?: string;
            status?: string;
            /** Format: int32 */
            sequenceOrder?: number;
            partType?: string;
            palletId?: string | null;
            /** Format: int32 */
            slotRow?: number;
            /** Format: int32 */
            slotColumn?: number;
            /** Format: date-time */
            createdAtUtc?: string;
            /** Format: date-time */
            updatedAtUtc?: string;
            /** Format: date-time */
            startedAtUtc?: string | null;
            /** Format: date-time */
            completedAtUtc?: string | null;
            errorMessage?: string | null;
            /** Format: int32 */
            version?: number;
        };
        TelemetrySampleDto: {
            id?: string;
            schemaVersion?: string;
            /** Format: date-time */
            timestampUtc?: string;
            sessionId?: string | null;
            runId?: string | null;
            equipmentId?: string;
            signalId?: string;
            /** Format: double */
            numericValue?: number | null;
            textValue?: string | null;
            valueType?: string;
            quality?: string;
            source?: string;
            origin?: string;
            correlationId?: string | null;
        };
        TelemetrySampleDtoHistorianPageDto: {
            items?: components["schemas"]["TelemetrySampleDto"][];
            /** Format: int64 */
            totalCount?: number;
            /** Format: int32 */
            skip?: number;
            /** Format: int32 */
            limit?: number;
        };
        UpdateMachineStateRequest: {
            simulationSessionId?: string | null;
            simulatorId?: string | null;
            machineMode?: string;
            simulationStatus?: string;
            robotState?: string;
            cncState?: string;
            currentPhase?: string;
            currentPalletId?: string | null;
            currentTaskId?: string | null;
            currentPartId?: string | null;
            /** Format: int32 */
            currentSlotRow?: number;
            /** Format: int32 */
            currentSlotColumn?: number;
            isRunning?: boolean;
            isPaused?: boolean;
        };
        UpdateSimulationStateRequest: {
            status?: string;
            currentPhase?: string;
            currentPalletId?: string | null;
            currentTaskId?: string | null;
            currentPartId?: string | null;
            /** Format: int32 */
            machinedCount?: number;
            /** Format: int32 */
            remainingCount?: number;
            /** Format: int32 */
            totalCount?: number;
            isPaused?: boolean;
            simulatorId?: string | null;
            correlationId?: string | null;
            scenarioId?: string | null;
            scenarioActivityId?: string | null;
            /** Format: int32 */
            scenarioProgress?: number | null;
        };
        UpdateTaskStatusRequest: {
            status: string;
            simulationSessionId: string;
            simulatorId: string;
            errorMessage?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
