import fs from 'node:fs'
import path from 'node:path'
import process from 'node:process'

const root = process.cwd()
const roadmapDir = path.join(root, 'docs', 'roadmap')
const registryPath = path.join(roadmapDir, 'roadmap.json')
const statePath = path.join(roadmapDir, 'state.json')
const currentPath = path.join(roadmapDir, 'CURRENT_SPRINT.md')

function fail(message) {
  console.error(`[sprint] ${message}`)
  process.exit(1)
}

function readJson(filePath) {
  if (!fs.existsSync(filePath)) fail(`Missing required file: ${path.relative(root, filePath)}`)
  return JSON.parse(fs.readFileSync(filePath, 'utf8'))
}

function writeJson(filePath, value) {
  fs.writeFileSync(filePath, `${JSON.stringify(value, null, 2)}\n`, 'utf8')
}

function load() {
  const roadmap = readJson(registryPath)
  const state = readJson(statePath)
  const knownIds = new Set(roadmap.sprints.map((sprint) => sprint.id))

  for (const sprint of roadmap.sprints) {
    state.sprints[sprint.id] ??= { status: 'planned' }
  }

  for (const id of Object.keys(state.sprints)) {
    if (!knownIds.has(id)) fail(`State references unknown sprint ${id}`)
  }

  return { roadmap, state }
}

function sprintById(roadmap, id) {
  return roadmap.sprints.find((sprint) => sprint.id === id)
}

function briefPath(sprint) {
  return path.join(root, sprint.file)
}

function renderCurrent(sprint, brief, stateEntry) {
  const header = [
    '<!-- Generated by scripts/sprint-runner.mjs. Do not edit this file directly. -->',
    '',
    `# Active sprint: ${sprint.id} - ${sprint.title}`,
    '',
    `Started: ${stateEntry.startedAt}`,
    '',
    'Source brief: [`' + sprint.file + '`](../../' + sprint.file.replaceAll('\\', '/') + ')',
    '',
    '## Execution contract',
    '',
    '1. Inspect the current implementation before changing files.',
    '2. Preserve existing behavior unless the brief explicitly changes it.',
    '3. Implement only this sprint and document discovered follow-up work.',
    '4. Add the tests required by this brief and run the applicable baseline gates.',
    '5. Do not mark the sprint complete while a required gate is failing.',
    '',
    '---',
    '',
  ].join('\n')

  fs.writeFileSync(currentPath, `${header}${brief.trim()}\n`, 'utf8')
}

function printSprint(sprint) {
  console.log(`[sprint] ${sprint.id} - ${sprint.title}`)
  console.log(`[sprint] Brief: ${sprint.file}`)
  console.log(`[sprint] Active brief: docs/roadmap/CURRENT_SPRINT.md`)
}

function status(roadmap, state) {
  const counts = { planned: 0, active: 0, completed: 0, blocked: 0 }
  for (const sprint of roadmap.sprints) {
    const value = state.sprints[sprint.id]?.status ?? 'planned'
    counts[value] = (counts[value] ?? 0) + 1
  }

  console.log(`[sprint] Roadmap: ${roadmap.name}`)
  console.log(`[sprint] Progress: ${counts.completed}/${roadmap.sprints.length} completed`)
  console.log(`[sprint] Planned=${counts.planned} Active=${counts.active} Blocked=${counts.blocked}`)

  if (state.activeSprint) {
    const sprint = sprintById(roadmap, state.activeSprint)
    if (sprint) printSprint(sprint)
  } else {
    const next = roadmap.sprints.find((sprint) => state.sprints[sprint.id]?.status === 'planned')
    console.log(next ? `[sprint] Next: ${next.id} - ${next.title}` : '[sprint] Roadmap complete')
  }
}

function startNext(roadmap, state) {
  if (state.activeSprint) {
    const active = sprintById(roadmap, state.activeSprint)
    if (!active) fail(`Unknown active sprint ${state.activeSprint}`)
    const brief = fs.readFileSync(briefPath(active), 'utf8')
    renderCurrent(active, brief, state.sprints[active.id])
    console.log('[sprint] An active sprint already exists; resuming it.')
    printSprint(active)
    return
  }

  const next = roadmap.sprints.find((sprint) => state.sprints[sprint.id]?.status === 'planned')
  if (!next) {
    console.log('[sprint] All roadmap sprints are complete.')
    return
  }

  const unmet = next.dependsOn.filter((id) => state.sprints[id]?.status !== 'completed')
  if (unmet.length > 0) fail(`${next.id} has unmet dependencies: ${unmet.join(', ')}`)

  const file = briefPath(next)
  if (!fs.existsSync(file)) fail(`Missing sprint brief: ${next.file}`)

  const startedAt = new Date().toISOString()
  state.activeSprint = next.id
  state.sprints[next.id] = { status: 'active', startedAt }
  state.updatedAt = startedAt
  writeJson(statePath, state)
  renderCurrent(next, fs.readFileSync(file, 'utf8'), state.sprints[next.id])

  console.log('[sprint] Activated next sprint.')
  printSprint(next)
  console.log('[sprint] Implement the active brief, run its gates, then complete it with:')
  console.log('npm run sprint:complete -- --summary "..." --evidence "..."')
}

function option(name) {
  const index = process.argv.indexOf(name)
  return index >= 0 ? process.argv[index + 1] : undefined
}

function complete(roadmap, state) {
  if (!state.activeSprint) fail('No active sprint to complete')
  const summary = option('--summary')
  const evidence = option('--evidence')
  if (!summary || !evidence) {
    fail('Completion requires --summary and --evidence. Evidence should list the executed test/build commands.')
  }

  const sprint = sprintById(roadmap, state.activeSprint)
  if (!sprint) fail(`Unknown active sprint ${state.activeSprint}`)

  const completedAt = new Date().toISOString()
  state.sprints[sprint.id] = {
    ...state.sprints[sprint.id],
    status: 'completed',
    completedAt,
    summary,
    evidence,
  }
  state.activeSprint = null
  state.updatedAt = completedAt
  writeJson(statePath, state)

  fs.writeFileSync(
    currentPath,
    `# No active sprint\n\nLast completed: **${sprint.id} - ${sprint.title}**\n\nRun \`npm run sprint:next\` to activate the next sprint.\n`,
    'utf8',
  )

  console.log(`[sprint] Completed ${sprint.id} - ${sprint.title}`)
  const next = roadmap.sprints.find((item) => state.sprints[item.id]?.status === 'planned')
  console.log(next ? `[sprint] Next: ${next.id} - ${next.title}` : '[sprint] Roadmap complete')
}

const command = process.argv[2] ?? 'status'
const { roadmap, state } = load()

switch (command) {
  case 'status':
    status(roadmap, state)
    break
  case 'start-next':
    startNext(roadmap, state)
    break
  case 'show': {
    if (!state.activeSprint) fail('No active sprint. Run npm run sprint:next first.')
    const sprint = sprintById(roadmap, state.activeSprint)
    printSprint(sprint)
    console.log(fs.readFileSync(currentPath, 'utf8'))
    break
  }
  case 'complete':
    complete(roadmap, state)
    break
  default:
    fail(`Unknown command '${command}'. Use status, start-next, show, or complete.`)
}
