import { createHash } from 'node:crypto'
import { readFile } from 'node:fs/promises'
import path from 'node:path'
import { describe, expect, it } from 'vitest'
import type { GLTF } from 'three/examples/jsm/loaders/GLTFLoader.js'
import { measureSceneResources } from './sceneMetrics'
import { parseGlbArrayBuffer } from './ThreeGlbAssetLoader'
import type { EquipmentAssetManifest } from './types'
import { PROFESSIONAL_ROBOT_ASSET_IDS, PROFESSIONAL_ROBOT_MANIFESTS } from './robotAssets'
import {
  HERO_CELL_DRESSING_ASSET_ID,
  HERO_CELL_DRESSING_MANIFEST,
  HERO_CNC_MACHINE_ASSET_ID,
  HERO_CNC_MACHINE_MANIFEST,
} from './heroAssets'

/**
 * S60 asset-pipeline coverage: the improved robot and hero-cell packages are
 * regenerated by `npm run assets:generate`. These tests re-read the committed
 * packages from disk, so a stale manifest, a renamed semantic node, a missing
 * LOD, an over-budget mesh or a lost license is caught before release.
 */

function packageDirectory(assetId: string): string {
  return path.join(process.cwd(), 'public', 'assets', 'equipment', assetId)
}

async function readBytes(file: string): Promise<Uint8Array> {
  return new Uint8Array(await readFile(file))
}

async function parseGlb(file: string): Promise<GLTF> {
  const bytes = await readBytes(file)
  const copy = new Uint8Array(bytes.byteLength)
  copy.set(bytes)
  return parseGlbArrayBuffer(copy.buffer)
}

async function generatedManifest(assetId: string): Promise<EquipmentAssetManifest> {
  return JSON.parse(await readFile(path.join(packageDirectory(assetId), 'equipment.asset.json'), 'utf8')) as EquipmentAssetManifest
}

function sha256(bytes: Uint8Array): string {
  return createHash('sha256').update(bytes).digest('hex')
}

async function semanticIds(assetId: string, file: string): Promise<Set<string>> {
  const gltf = await parseGlb(path.join(packageDirectory(assetId), file))
  const ids = new Set<string>()
  gltf.scene.traverse((node) => {
    if (typeof node.userData?.semanticId === 'string') ids.add(node.userData.semanticId)
    if (node.name) ids.add(node.name)
  })
  return ids
}

describe('S60 robot asset pipeline', () => {
  it('keeps the TypeScript robot manifests byte-identical to the generated packages', async () => {
    for (const size of ['compact', 'medium', 'heavy'] as const) {
      const manifest = PROFESSIONAL_ROBOT_MANIFESTS[size]
      expect(await generatedManifest(manifest.id), manifest.id).toEqual(manifest)
    }
  })

  it('recomputes every robot hash and keeps the primary inside its budget and bounds', async () => {
    for (const id of Object.values(PROFESSIONAL_ROBOT_ASSET_IDS)) {
      const manifest = Object.values(PROFESSIONAL_ROBOT_MANIFESTS).find((candidate) => candidate.id === id)!
      const directory = packageDirectory(id)
      for (const file of ['model.glb', 'lod/lod1.glb']) {
        const declared = file === 'model.glb' ? manifest.visual.glb.sha256 : manifest.visual.lods[0]!.glb.sha256
        expect(sha256(await readBytes(path.join(directory, file))), `${id}/${file}`).toBe(declared)
      }
      const primary = measureSceneResources((await parseGlb(path.join(directory, 'model.glb'))).scene)
      expect(primary.triangles, id).toBeLessThanOrEqual(25_000)
      const lod = measureSceneResources((await parseGlb(path.join(directory, 'lod/lod1.glb'))).scene)
      expect(lod.triangles, id).toBeLessThanOrEqual(manifest.visual.lods[0]!.triangleBudget)
      expect(lod.triangles, id).toBeLessThan(primary.triangles)
    }
  })

  it('preserves the six semantic pivots and tool frames and declares the rig and license', async () => {
    for (const id of Object.values(PROFESSIONAL_ROBOT_ASSET_IDS)) {
      const manifest = Object.values(PROFESSIONAL_ROBOT_MANIFESTS).find((candidate) => candidate.id === id)!
      const ids = await semanticIds(id, 'model.glb')
      for (const node of ['joint:j1', 'joint:j2', 'joint:j3', 'joint:j4', 'joint:j5', 'joint:j6', 'tool:flange', 'tool:tcp']) {
        expect(ids.has(node), `${id} missing ${node}`).toBe(true)
      }
      // S60 visual detail: a generic two-finger gripper is present on the tool.
      expect(ids.has('gripper:body'), `${id} missing gripper:body`).toBe(true)
      expect(ids.has('gripper:finger-left')).toBe(true)
      expect(manifest.robotRig?.joints.map((joint) => joint.axis)).toEqual(['y', 'z', 'z', 'x', 'z', 'x'])
      expect(manifest.robotRig?.flangeNode).toBe('tool:flange')
      expect(manifest.robotRig?.toolFrameNode).toBe('tool:tcp')
      expect(manifest.license.name).toContain('Fabrik3D generated')
    }
  })

  it('keeps semantic pivots and tool frames in the LOD while dropping fine detail', async () => {
    const ids = await semanticIds(PROFESSIONAL_ROBOT_ASSET_IDS.medium, 'lod/lod1.glb')
    for (const node of ['joint:j1', 'joint:j2', 'joint:j3', 'joint:j4', 'joint:j5', 'joint:j6', 'tool:flange', 'tool:tcp']) {
      expect(ids.has(node), `LOD missing ${node}`).toBe(true)
    }
    // Purposeful LOD: the small bolt/decals are not on the reduced silhouette.
    expect(ids.has('label:warning-2')).toBe(false)
  })

  it('targets the professional robot bounds range and never copies an OEM asset', async () => {
    expect(PROFESSIONAL_ROBOT_MANIFESTS.compact.boundsMeters.x).toBeLessThan(PROFESSIONAL_ROBOT_MANIFESTS.medium.boundsMeters.x)
    expect(PROFESSIONAL_ROBOT_MANIFESTS.medium.boundsMeters.x).toBeLessThan(PROFESSIONAL_ROBOT_MANIFESTS.heavy.boundsMeters.x)
    for (const manifest of Object.values(PROFESSIONAL_ROBOT_MANIFESTS)) {
      expect(manifest.license.name).not.toMatch(/fanuc|abb|kuka|yaskawa|motoman|staubli/i)
      expect(manifest.semanticNodes.map((node) => node.id)).not.toContain('vendor:oem')
    }
  })
})

describe('S60 hero-cell asset pipeline', () => {
  it('keeps the TypeScript hero manifests byte-identical to the generated packages', async () => {
    expect(await generatedManifest(HERO_CNC_MACHINE_ASSET_ID)).toEqual(HERO_CNC_MACHINE_MANIFEST)
    expect(await generatedManifest(HERO_CELL_DRESSING_ASSET_ID)).toEqual(HERO_CELL_DRESSING_MANIFEST)
  })

  it('adds moderate CNC and environment detail while staying inside the documented budgets', async () => {
    const cnc = measureSceneResources((await parseGlb(path.join(packageDirectory(HERO_CNC_MACHINE_ASSET_ID), 'model.glb'))).scene)
    const cncLod = measureSceneResources((await parseGlb(path.join(packageDirectory(HERO_CNC_MACHINE_ASSET_ID), 'lod/lod1.glb'))).scene)
    expect(cnc.triangles).toBeLessThanOrEqual(16_000)
    expect(cncLod.triangles).toBeLessThanOrEqual(HERO_CNC_MACHINE_MANIFEST.visual.lods[0]!.triangleBudget)
    expect(cncLod.triangles).toBeLessThan(cnc.triangles)

    const dressing = measureSceneResources((await parseGlb(path.join(packageDirectory(HERO_CELL_DRESSING_ASSET_ID), 'model.glb'))).scene)
    const dressingLod = measureSceneResources((await parseGlb(path.join(packageDirectory(HERO_CELL_DRESSING_ASSET_ID), 'lod/lod1.glb'))).scene)
    expect(dressing.triangles).toBeLessThanOrEqual(12_000)
    expect(dressingLod.triangles).toBeLessThanOrEqual(HERO_CELL_DRESSING_MANIFEST.visual.lods[0]!.triangleBudget)
  })

  it('exposes the improved CNC and environment semantic nodes', async () => {
    const cnc = await semanticIds(HERO_CNC_MACHINE_ASSET_ID, 'model.glb')
    for (const node of [
      'door:loading', 'door:inner', 'spindle:main', 'fixture:chuck', 'fixture:jaw-left', 'fixture:jaw-right',
      'axis:feed', 'coolant:nozzle', 'panel:button:1', 'signal:panel-screen', 'signal:stack-light',
      'machine:panel:1', 'machine:rail:1', 'chamber:back', 'machine:work-light-2', 'cable:chain:0',
      'marking:footprint-front', 'label:safety-1',
    ]) {
      expect(cnc.has(node), `CNC missing ${node}`).toBe(true)
    }

    const dressing = await semanticIds(HERO_CELL_DRESSING_ASSET_ID, 'model.glb')
    for (const node of [
      'motor:chip-conveyor', 'chip:pump', 'fixture:buffer:1', 'fixture:buffer:2',
      'signal:worklight:1', 'signal:worklight:2', 'cabinet:electrical:1', 'cabinet:electrical:2',
      'marking:pedestrian:left', 'marking:zone:front', 'label:cell',
    ]) {
      expect(dressing.has(node), `dressing missing ${node}`).toBe(true)
    }
  })
})
